config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios, except: [:show]
  get 'angular-items', to: "portfolios#angular"
  get 'portfolio/:id', to: "portfolios#show", as: "portfolio_show" # The nameing should have been added at video 66

  get 'about-me', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
end

app/models/blog.rb
class Blog < ApplicationRecord
enum status: { draft: 0, published: 1 }

  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic, optional: true

  def self.special_blogs
    Blog.all
  end

  def self.featured_blogs
    Blog.limit(2)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  layout "blog"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all


  # GET /blogs or /blogs.json
  def index
    @blogs = Blog.page(params[:page]).per(5)
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    @page_title = @blog.title
    @seo_keywords = @blog.body
  end

  # GET /blogs/new
  def new 
    @blog = Blog.new #AZ-35: this is to make the form available to us
  end

  # GET /blogs/1/edit
  def edit #AZ-35: This is in the before_action list, but I don't know how this knows automatically to call update. learn how later.
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params) #AZ-35: this creates the blog using the parameters

    respond_to do |format| #AZ-35: learn more about format later.
      if @blog.save #AZ-35: checks if they are valid. learn more later
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully created." }
        # format.html { redirect_to @blog, notice: "Blog was successfully created." } #AZ-35: this was the one he used in the course. It worked fine. learn more about Rails 5 vs Rails 7 later.
        format.json { render :show, status: :created, location: @blog } #AZ-35: this is not needed. It works completly fine without it.
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity } #AZ-35: this is not needed. It works completly fine without it.
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params) #AZ-35: this udates & checkes if updated. learn more later
        format.html { redirect_to blog_url(@blog), notice: "Blog was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy #AZ-35: this will delete the record from the database

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    @blog.draft? ? @blog.published! : @blog.draft!
    redirect_to blogs_url, notice: "Post status has been updated"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title, :body) #AZ-35: what is this? learn what later.
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title, blog, class: "text-decoration-none" %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <% if logged_in?(:site_admin) %>

    <p class="blog-post-meta">
      <%= link_to blog.status, toggle_status_blog_path(blog), class: "text-decoration-none" %> /
      <%= link_to 'Edit', edit_blog_path(blog), class: "text-decoration-none" %> /
      <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
    
  <% end %>

  <p>
    <%= blog.body %>
  </p>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", rows: 12 %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: "btn btn-primary" %>
    
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editing blog</h1>

  <%= render "form", blog: @blog %>

  <div>
    <%= link_to "Show this blog", @blog %> |
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/index.html.erb
 <div class="col-sm-8 blog-main">
  
  <%= paginate @blogs %>

  <%= render partial: @blogs %>

  <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">

  <h1>New blog</h1>

  <%= render "form", blog: @blog %>

  <div>
    <%= link_to "Back to blogs", blogs_path %>
  </div>
</div>

app/views/blogs/show.html.erb
 <div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>
  
    <%= link_to "Edit", edit_blog_path(@blog) if logged_in?(:site_admin) %> 
  
  <p>
    <%= @blog.body %>
  </p>

</div>