config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "", path_names: { sign_in: "login", sign_out: "logout", sign_up: "register" }
  resources :portfolios, except: [:show]
  get 'angular-items', to: "portfolios#angular"
  get 'portfolio/:id', to: "portfolios#show", as: "portfolio_show" # The nameing should have been added at video 66

  get 'about-me', to: "pages#about"
  get 'contact', to: "pages#contact"

  resources :blogs do 
    member do
      get :toggle_status
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root "pages#home"
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  accepts_nested_attributes_for :technologies, 
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    self.where(subtitle: 'Angular')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: %i[ edit update show destroy ]
  layout "portfolio"
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.all
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: "Your portfolio item is now live." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: "The portfolio item is successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def show
  end

  def destroy
    # Destroy/delete the record
    @portfolio_item.destroy

    # Redirect
    respond_to do |format|
      format.html { redirect_to portfolios_path, notice: 'Portfolio was removed.'}
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:name]
                                      )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "https://via.placeholder.com/#{height}X#{width}"
  end

  def portfolio_img(img, type)
    if img.model.main_image? || img.model.thumb_image?
      img.url
    elsif type == "thumb"
      image_generator(height: "350", width: "200")
    else
      image_generator(height: "600", width: "400")
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_with(model: @portfolio_item) do |form| %>
  
  <div class="row">
    <div class="col-md-6">

      <div class="form-group">
        <%= form.label :title, style: "display: block" %>
        <%= form.text_field :title, class: "form-control" %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle, style: "display: block" %>
        <%= form.text_field :subtitle, class: "form-control" %>
      </div>

      <br>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: "display:none" %>
        </label>
      </div>

      <br>
      <div class="form-group">
        <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :thumb_image, style: "display:none" %>
        </label>
      </div>
    </div>


    <div class="col-md-6">

      <div class="form-group">
        <%= form.label :body, style: "display: block" %>
        <%= form.text_area :body, class: "form-control", rows: 9 %>
      </div>

    </div>
  </div>

  
  <hr>

  <div class="col-md-12">
    
    <h2>Technologies Used:</h2>

    <div>
      <%= form.fields_for :technologies do |technology_form| %>
        <div class="form-group">
          <%= technology_form.label :tech %>
          <%= technology_form.text_field :name, class: "form-control" %>
        </div>
      <% end %>
    </div>

  </div>

  <br>

  <div class="form-group">
    <%= form.submit "Save Portfolio Item", class: "btn btn-primary w-100" %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card">
  <%= image_tag portfolio_img(portfolio_item.thumb_image, "thumb"), width: "100%", height: "100%" %>  
  <p class="card-text">
    <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
  </p>
</div>

app/views/portfolios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to "Create New Item", new_portfolio_path if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
  <p> <%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
  <p> <%= portfolio_item.subtitle %></p>
  <p> <%= portfolio_item.body %></p>
  <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
  <%= link_to "Edit this portfolio", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>

<!-- The other 2 ways did not work. check the notes-->

  <%= link_to "Delete Porfolio", portfolio_path(portfolio_item), data: { "turbo-method": :delete, confirm: 'Are you sure?'} if logged_in?(:site_admin) %>
<% end%>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">

  <h1> Edit this Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>

</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row sortable">

      <%= render partial: "portfolio_item", collection: @portfolio_items %>
      
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">

  <h1> Create a new Portfolio Item</h1>

  <%= render "form", portfolio_item: @portfolio_item %>

</div>
  

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
        <p><%= t.name %></p>
      <% end %>

      
    </div>
    
    <div class="col-md-5">
      
      <p><%= image_tag portfolio_img(@portfolio_item.main_image, "main"), width: "100%" %></p> 

    </div>
  </div>
</div>